### ISSUE TITLE
Remove duplicate "aeson" dependency

### ISSUE THREAD

**Issue by markborkum** [pbrisbin/codeclimate-hlint#12]
The files `Build.dockerfile` and `engine.cabal` both duplicate the dependency statement for the "aeson" library.

**Comment by pbrisbin** [comment]
Thanks for letting me know, however that's intentional. By pre-installing large dependencies in their own layer, you don't bust that layer cache whenever you touch the Cabal file. I don't do it for all dependencies, but those that take a while to build and are unlikely to be removed any time soon are good candidates.

By the way, this project is very close to being deprecated. The machinery for being an engine was merged upstream, so as soon as CC releases an engine based on those sources I can shut this down. This'll bring a new version, more stable behavior, and better support for the various HLint options all to the CC engine version.

**Comment by markborkum** [comment]
This is great news!

This is the first of two new issues that would have been followed by a pull request. For the benefit of my employer, would you mind if I submit the second issue and the pull request? (Please feel free to close them.)

**Comment by pbrisbin** [comment]
Sure, feel free :)
